weather_analytics:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: weather.duckdb
      extensions:
        - httpfs
      settings:
        s3_endpoint: "localhost:8333"
        s3_access_key_id: "any_key_local"
        s3_secret_access_key: "any_secret_local"
        s3_use_ssl: "false"
        s3_url_style: "path"